github:
  description: "Apache XML Graphics Website"
  homepage: https://xmlgraphics.apache.org
  labels:
    - xmlgraphics
    - apache
  protected_branches:
    master:
      required_linear_history: true

staging:
  profile: ~
  whoami:  asf-staging

pelican:
  whoami: master
  target: asf-site
 
publish:
  whoami: asf-site
